### PR TITLE
Project improvements : proposals from Android Studio

### PR DESCRIPTION
**Pull request by williamdes**
I applied some of the propositions that Android Studio inspector found in Silence.
I let you cherry-pick the commits that you want.

For me the more usefull commits are :
- "SDK_INT is never <9 because minSdkVersion 9"
- "Removed unused import statements"
- "[Manual] Missing supercall fix "

I will push more commits on this PR soon.

I hope @BLeQuerrec that you will accept some of the proposals from Android Studio.
Let me know what you think about all that.

### CODE REVIEW

**Comment by williamdes** [comment]
Is this normal ?
silence_min_sdk

**Comment by williamdes** [comment]
silence_min_sdk_2

**Comment by williamdes** [comment]
@BLeQuerrec did you have time to review this PR ?
Should we migrate ```com.android.support.support-v4``` to ```com.android.support.support-v7``` ?

**Comment by BLeQuerrec** [comment]
Thanks! I'll merge the PR in a single commit. Don't rebase your branch, I'll do it myself.
But can you explain 6bd009e46e8bc335b4eb229305c58dade63190af and c5c140ef6758e9fad2f9d5f8151cccaae1548c3c? Is it a performance improvement?

**Comment by williamdes** [comment]
Thank you !

It is a performance improvement (I didn't verify).
It is also easier to read a foreach.

Some StackOverflow threads say that they got better performance with the use of a foreach
See: [Performance of traditional for loop vs Iterator/foreach in Java
](https://stackoverflow.com/questions/1879255/performance-of-traditional-for-loop-vs-iterator-foreach-in-java)

What do you think about the API level screens ?
And the support v4 question ?

**Comment by BLeQuerrec** [comment]
I'll investigate the warnings about API levels later.
For now, we'll keep the v4 support lib to be as close as possible to Signal code base.

**Comment by williamdes** [comment]
No problem, thank you for your answer :)

**Pull request closed without merging**
