### PR TITLE
Build with circleCI

### PR DESCRIPTION
**Pull request by zoff99**
build commands for circleCI

https://circleci.com/gh/zoff99/Silence/8#artifacts

https://circle-artifacts.com/gh/zoff99/Silence/8/artifacts/0/tmp/circle-artifacts.Zmamicg/capture_app_running.png

capture_app_running

### CODE REVIEW

**Comment by zoff99** [comment]
is this something you want to merge in?

**Comment by BastienLQ** [comment]
Thanks for your PR, @zoff99! What's the difference between CircleCI and TravisCI? Additionally, why don't you build the tests and why do you update the signature of the build?

**Comment by zoff99** [comment]
circleCI stores all artifacts for a long time and everybody to download (apk files, images, usw.)

see: https://circleci.com/gh/zoff99/Silence/8#artifacts

**Comment by zoff99** [comment]
how do you build the tests?
i don't see any tests defined in .travis.yml
would be good to merge this, for people to build their forks and PRs

**Comment by BastienLQ** [comment]
Tests can be built with `./gradlew connectedCheck`. Every TravisCI build is uploaded to https://files.silence.im/ (I clean up uploads sometimes, I did it last hour). So we're not going to merge this.

**Pull request closed without merging**
