### PR TITLE
Linkify geo and xmpp URIs

### LINKED ISSUE #501: Silence doesn't support Geo URIs
I recently have got a text with following content:
`geo:47.1234,8.1234?z=14`
(it was generated by osmand~)
I would like to open this Geo URI with an app which can handle Geo-Location Data (for example for directions, osmand~, ...)

There is also a RFC for Geo URIs:
https://tools.ietf.org/rfc/rfc5870.txt
https://en.wikipedia.org/wiki/Geo_URI_scheme

### PR DESCRIPTION
**Pull request by BLeQuerrec**
### Description

This PR linkify geo: and xmpp: URIs, and catch exceptions to do not crash if no app is installed on user's phone to manage these links.

Fixes #501

### CODE REVIEW

**Comment by pR0Ps** [comment]
I tested this by sharing a geo link to a conversation (`geo:10.69890,-150.62300`)

When loading into the conversation, the link works properly. However, when selecting a message, then deselecting it, the linking falls back to (what I assume is) the default which is to link the individual parts of it as numbers. When clicking again, the phone application opens, trying to call `106-9890`.

The same thing happens when writing a message with a geo link in it (not properly linked until you go back, then open the conversation again) or when clicking the link and opening a mapping application, then hitting back.

**Comment by BLeQuerrec** [comment]
Fixed.

**Comment by pR0Ps** [comment]
I found a few more issues:
 1. `Http://example.org` (notice the capital) didn't link properly
 2. `example.org` didn't link properly
 3. `user@example.org` when clicking the domain part, it would fire an intent to view the domain, not the email address. Combine this with 1 for extra frustration.
 4. No real feedback on why something doesn't work. It's underlined, you click it, but nothing happens.

I've been messing around with this for a bit and I've got something that handles all these issues, mind if I push it on top of this branch? Can squash/revert it once you review it.

**Comment by pR0Ps** [comment]
There's still an issue with overlapping links but it's a pretty small edge case and requires malformed links.

For example, take `geo:111,222.333 444`
 - `geo:111,222.333` would be linked under the `geo:`scheme (correct)
 - `222.333 444` would be linked under the `tel:` scheme (incorrect)
 - However, due to the order links are added, clicking anywhere but the trailing ` 444` would open the `geo:` link.
 - The ` 444` is still underlined though which could be confusing for the user when they click the link and only part of it is used.

I don't think there's a nice way to get access to the underlying links without basically rewriting the `Linkify` class. When the `bodyText` is modified, the links are added, but I don't know if it's possible to (nicely) get the link information (start, end, link type, etc) back out of it. This prevents us from writing something like `Linkify.pruneOverlaps` (private function, seems unused) to fix this problem.

**Pull request merged**
