### PR TITLE
Add delete button to notifications

### PR DESCRIPTION
**Pull request by pR0Ps**
This commit adds a delete buttons to new message notifications. The
option is available in both single and multi-recipient notifications.

It also changes the size of the button icons (for Android versions that
support them) to a more standard size (24dp).

The use case for this feature is for things like spam messages, 2FA codes, and other messages that don't matter anymore after they've been read (Ex: "your monthly bill is blah")

### CODE REVIEW

**Comment by BastienLQ** [comment]
It's quite dangerous. A button to archive conversation(s) would be
better, in my opinion.

**Comment by pR0Ps** [comment]
Unfortunately I don't think archiving from the notification would really work since the archive action works on threads, not individual messages.

My email app has had a "delete" action in the notification since I started using it and I can't say I've ever accidentally pressed it. That being said, I understand that there is a risk. Would having an option under the "Notifications" section to enable/disable be an acceptable compromise?

**Comment by bmenant** [comment]
Another use-case is 2FA (tow factors authentication) messages, i.e. temporary confirmation codes you receive to sign in or pay on-line. There’s is no sense to archive such messages.
Yet personally, I’ve never archived any message from a notification, while I do archive conversations from the app. 
It might be useful for some folks though.
I vote 👍 for having the option to choose between an archive or delete action within notifications.

**Comment by pR0Ps** [comment]
Rebased off the current master

**Pull request closed without merging**
